config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'clock_events#index'
  resources :clock_events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clock_event.rb
class ClockEvent < ApplicationRecord
  validates :name, presence: true
  validates :clock_type, presence: true
end

app/models/time_clock.rb
class TimeClock < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/clock_events_controller.rb
class ClockEventsController < ApplicationController
  def index
    @clock_events = ClockEvent.paginate(:page => params[:page], :per_page => 20)
  end
  
  def new
    @clock_event = ClockEvent.new
  end
  
  def create
    @clock_event = ClockEvent.new(clock_events_params)
    
    if @clock_event.save
      redirect_to clock_events_path
      flash[:success] = "Successfully created"
    else
      flash[:alert] = "Please enter a name"
      render :new
    end
  end
  
  def edit
    @clock_event = ClockEvent.find(params[:id])
  end
  
  def update
    @clock_event = ClockEvent.find(params[:id])
    
    if @clock_event.update(clock_events_params)
      redirect_to clock_events_path
      flash[:success] = "Successfully updated"
    else
      flash[:alert] = "Update failed"
      render :edit
    end
  end
  
  def destroy
    @clock_event = ClockEvent.find(params[:id])
    
    if @clock_event.destroy
      redirect_to clock_events_path
      flash[:success] = "Successfully deleted"
    else
      flash[:alert] = "Delete failed"
    end
  end
  
  private
  
  def clock_events_params
    params.permit(:name, :clock_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bulma_class_for(flash_type)
    case flash_type
    when "success"
      "is-success"
    when "alert"
      "is-warning"
    else
      "is-primary"
    end
  end
end

app/helpers/clock_events_helper.rb
module ClockEventsHelper
end

app/views/clock_events/edit.html.erb
<div class="column is-half is-offset-one-quarter">
  <div class="box">
    <%= form_tag  clock_event_path, method: :patch do %>
    <div class="card-content">
      <%= label_tag "Name", nil, class: "label" %>
      <%= text_field_tag :name, @clock_event.name, class: "input" %>
      <%= label_tag "Clock Type", nil, class: "label" %>
      <div class="select">
        <%= select_tag :clock_type, options_for_select(TimeClock.pluck(:category), selected: @clock_event.clock_type) %>
      </div>
    </div>  
  </div>
  <div class="is-pulled-right">
    <%= submit_tag "Update", class: "button is-primary" %>
    
    <%= link_to "Back", clock_events_path, class: "button" %>
  </div>
  <% end %>
</div>

app/views/clock_events/index.html.erb
<table class="table datatable is-hoverable is-fullwidth">
  <thead>
  <tr>
    <th>Clock Event ID</th>
    <th>Name</th>
    <th>Clock Type</th>
    <th>Time</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @clock_events.order(created_at: :desc).each do |clock_event| %>
    <tr>
      <td><%= clock_event.id %></td>
      <td><%= clock_event.name %></td>
      <td><%= clock_event.clock_type %></td>
      <td><%= clock_event.created_at %></td>
      <td>
        <%= link_to "Edit", edit_clock_event_path(clock_event), class: "button" %>
        <%= button_to "Delete", clock_event_path(clock_event.id), method: :delete, class: "button is-danger", form: {style: "display:inline-block;"}%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @clock_events, container: false %>

app/views/clock_events/new.html.erb
<div class="column is-half is-offset-one-quarter">
  <div class="box">
    <%= form_tag  clock_events_path, method: :create do %>
    <div class="card-content">
      <div class="field">
        <%= label_tag "Name", nil, class: "label" %>
        <%= text_field_tag :name, "", class: "input" %>
        <br/>
        <%= label_tag "Clock Type", nil, class: "label" %>
        <div class="select">
          <%= select_tag :clock_type, options_for_select(TimeClock.pluck(:category)) %>
        </div>
      </div>
    </div>  
  </div>
  <div class="is-pulled-right">
    <%= submit_tag "Submit", class: "button is-primary" %>
    <%= link_to "Back", clock_events_path, class: "button" %>
  </div>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
<div class="column is-half is-offset-one-quarter">
  <div class="notification has-text-centered <%= bulma_class_for(type) %>"><%= message %></div>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="aa-navbar navbar is-dark">
  <div class="container">
    <div class="navbar-menu">
      <div class="navbar-start">
        <%= link_to "Clock Events", clock_events_path, class: "navbar-item" %>
        <%= link_to "Create Clock Event", new_clock_event_path, class: "navbar-item" %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clock Events</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "clock_events", media: "all", "data-turbolinks-track": "reload" %>
</head>
<body>
  <%= render "layouts/navigation" %>
  <%= render "layouts/messages" %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>